openapi: 3.2.0
info:
  title: Cube Scenarios API
  version: 1.0.0 (1.0)
  description: '#### General Description

    An API to access underlying Cube functionality.'
  termsOfService: https://www.cubesoftware.com/terms-of-service
servers:
- url: https://api.cubesoftware.com
  description: Production API URL
tags:
- name: Scenarios
paths:
  /dimensions/scenarios/variance-analysis:
    post:
      operationId: dimensions_scenarios_variance_analysis_create
      description: This class exists to have a standard rate limit across all authenticated API endpoints
      parameters:
      - in: header
        name: X-Company-ID
        schema:
          type: string
        description: Associates request with company
        required: true
      tags:
      - Scenarios
      security:
      - OAuth2: []
      responses:
        '200':
          description: No response body
      summary: Dimensions scenarios variance analysis create
      x-summary-source: derived
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://portal.cubesoftware.com/o/authorize/
          tokenUrl: https://api.cubesoftware.com/o/token/
          scopes: {}
      description: Standard Cube OAuth 2.0 flow
